# Ejercicios sobre vectores y matrices complejos semana 2
## Daniel Felipe Ruiz Bermúdez

### Ejercicio 1. suma de dos vectores complejos
Dado dos vectores complejos
$ v1 = \begin{bmatrix} 1 + 2i \\ 3 - i \end{bmatrix} $ 
y 
$ v2 = \begin{bmatrix} 2 - i \\ 4 + 2i \end{bmatrix} $, 
find their sum.

In [2]:
import numpy as np

v1 = np.array([[1 + 2j], [3 - 1j]])
v2 = np.array([[2 - 1j], [4 + 2j]])
suma = v1 + v2
suma

array([[3.+1.j],
       [7.+1.j]])

### Ejercicio 2: Negación de un vector complejo
Dado un vector complejo 
$ v = \begin{bmatrix} 2 + 3i \\ 1 - 2i \end{bmatrix} $, 
encontrar su negación.

In [4]:
vn = np.array([[2 + 3j], [1 - 2j]])
negac = -vn
negac

array([[-2.-3.j],
       [-1.+2.j]])

### Ejercicio 3: Multiplicación de un vector complejo por un escalar
Multiplicar el vector complejo 
$ v = \begin{bmatrix} 1 - i \\ 2 + 2i \end{bmatrix} $ 
por el complejo escalar $$ 3 + i $$.

In [8]:
vc = np.array([[1 - 1j], [2 + 2j]])
sc = 3 + 1j
multEscVc = vc * sc
multEscVc

array([[4.-2.j],
       [4.+8.j]])

### Ejercicio 4: Transpuesta de un vector complejo
Encontrar la transpuesta del vector complejo 
$ v = \begin{bmatrix} 2 - i \\ 3 + 4i \end{bmatrix} $.

In [11]:
v = np.array([[2 - 1j], [3 + 4j]])
transpV = v.T
(v, transpV)

(array([[2.-1.j],
        [3.+4.j]]),
 array([[2.-1.j, 3.+4.j]]))

### Ejercicio 5: Conjugado de un vector complejo
Computar el conjugado del vector complejo 
$ v = \begin{bmatrix} 1 + i \\ 2 - 3i \end{bmatrix} $.

In [12]:
vect = np.array([[1 + 1j],[2 - 3j]])
vectConjug = np.conjugate(vect)
vectConjug

array([[1.-1.j],
       [2.+3.j]])

### Ejercicio 6: Adjunta (Conjugada Transpuesta) de un vector complejo
Encontrar la adjunta (o transpuesta conjugada) del vector complejo 
$ v = \begin{bmatrix} 1 - 2i \\ 3 + i \end{bmatrix} $.

In [13]:
vector = np.array([[1 - 2j], [3 + 1j]])
conjugVector = np.conjugate(vector)
transpConjug = conjugVector.T
transpConjug

array([[1.+2.j, 3.-1.j]])

## Operaciones de matrices cuadradas complejas

### Ejercicio 7: Suma de dos matrices complejas
Dadas dos matrices complejas 
$ m1 = \begin{bmatrix} 1 + i & 2 - i \\ 3 + 2i & 4 \end{bmatrix} $
y 
$ m2 = \begin{bmatrix} 2 - 3i & 1 \\ i & 2 + 2i \end{bmatrix} $, 
calcular su suma.

In [24]:
m1 = [[1 + 1j, 2 - 1j],
    [3 + 2j, 4]]

m2 = [[2 - 3j, 1],
    [0 + 1j, 2 + 2j]]

def sumaMatrices(matr1, matr2):
    matr1 = np.array(matr1)
    matr2 = np.array(matr2)
    suma = matr1 + matr2
    return suma
print(sumaMatrices(m1,m2))

[[3.-2.j 3.-1.j]
 [3.+3.j 6.+2.j]]


### Ejercicio 8: Negación de una matriz compleja
Encontrar la negación de la matriz compleja 
$ m = \begin{bmatrix} 2 + i & 3 \\ 1 - i & 2 + 2i \end{bmatrix} $.

In [29]:
m = np.array([[2 + 1j, 3],
              [1 - 1j, 2 + 2j]])

def negacion(ma):
    negMa = -ma
    return negMa

print(negacion(m))

[[-2.-1.j -3.-0.j]
 [-1.+1.j -2.-2.j]]


### Ejercicio 9: Multiplicacion de una matriz compleja por un escalar
Multiplicar la matriz compleja 
$ m = \begin{bmatrix} 1 - i & 2 \\ 3 + i & 4 - 2i \end{bmatrix} $ 
por el escalar complejo $$ 2 + 3i $$.

In [30]:
def scPorMatrizComplx(sc, matr):
    result = matr * sc 
    return result

sc = 2 + 3j
matr = np.array([[1 - 1j, 2], 
                 [3 + 1j, 4 - 2j]])

print(scPorMatrizComplx(sc, matr))

[[ 5. +1.j  4. +6.j]
 [ 3.+11.j 14. +8.j]]


### Ejercicio 10: Conjugado de una matriz compleja
Computar la conjugada de la matriz compleja 
$ m = \begin{bmatrix} 1 + i & 2 \\ 3 - i & 4 + 2i \end{bmatrix} $.

In [31]:
def conjugMatr(m):
    conjugM = np.conjugate(m)
    return conjugM 

m = np.array([[1 + 1j, 2],
              [3 - 1j, 4 + 2j]])

print(conjugMatr(m))

[[1.-1.j 2.-0.j]
 [3.+1.j 4.-2.j]]


### Ejercicio 11: Transpuesta de matriz compuesta
Encontrar la transpuesta de la matriz compleja 
$ m = \begin{bmatrix} 1 - i & 2 + 2i \\ 3 & 4 - i \end{bmatrix} $.

In [32]:
def transpMatr(m):
    transpM = m.T
    return transpM 

m = np.array([[1 - 1j, 2 + 2j], [3, 4 - 1j]])

print(transpMatr(m))

[[1.-1.j 3.+0.j]
 [2.+2.j 4.-1.j]]


### Ejercicio 12: Adjunta (conjugada transpuesta) de matriz compleja
Calcular la adjunta (o conjugada transpuesta) de la matriz compleja 
$ m = \begin{bmatrix} 1 + 2i & 3 - i \\ 4 & 5 + i \end{bmatrix} $.

In [33]:
def adjMatr(m):
    conjugMt = conjugMatr(m)
    adjuntaMt = transpMatr(conjugMt)
    return adjuntaMt 

m = np.array([[1 + 2j, 3 - 1j],
              [4, 5 + 1j]])

print(adjMatr(m)) 

[[1.-2.j 4.-0.j]
 [3.+1.j 5.-1.j]]


### Ejercicio 13: Chequear las dimensiones de la Matriz
Determinar las dimensiones de la matriz compleja 
$ m = \begin{bmatrix} 1 - i & 2 \\ 3 + 2i & 4 - i \end{bmatrix} $.

In [35]:
def numDimMatr(m):
    return m.shape

m = np.array([[1 - 1j, 2],
      [3 + 2j, 4 - 1j]])

print(numDimMatr(m))


(2, 2)


### Ejercicio 14: Multiplicar una Matriz cuadrada compleja por un vector columna complejo
Multiplicar la matriz cuadrada compleja 
$ m = \begin{bmatrix} 1 + i & 2 - i \\ 3 & 4 + i \end{bmatrix} $ 
por el vector columna complejo 
$ v = \begin{bmatrix} 2 - i \\ 1 + 3i \end{bmatrix} $.

In [37]:
def matrPorVector(m, v):
    resultado = np.dot(m, v)
    return resultado 

m = np.array([[1 + 1j, 2 - 1j],
              [3, 4 + 1j]])

v = np.array([[2 - 1j],
              [1 + 3j]])

print(matrPorVector(m, v))

[[8. +6.j]
 [7.+10.j]]
